/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * API version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package lib

// Segment ids and List ids to include/exclude from campaign
type CreateWhatsAppCampaignRecipients struct {
	// List ids to exclude from the campaign
	ExcludedIds []int64 `json:"excludedIds,omitempty"`
	// **Mandatory if scheduledAt is not empty**. List Ids to send the campaign to
	ListIds []int64 `json:"listIds,omitempty"`
	// **Mandatory if listIds are not used**. Segment ids to send the campaign to.
	Segments []int64 `json:"segments,omitempty"`
}
