/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * API version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package lib

// List of enable/disable applications on the sub-account
type SubAccountAppsToggleRequest struct {
	// Set this field to enable or disable Inbox on the sub-account / Not applicable on ENTv2
	Inbox bool `json:"inbox,omitempty"`
	// Set this field to enable or disable Whatsapp campaigns on the sub-account
	Whatsapp bool `json:"whatsapp,omitempty"`
	// Set this field to enable or disable Automation on the sub-account
	Automation bool `json:"automation,omitempty"`
	// Set this field to enable or disable Email Campaigns on the sub-account
	EmailCampaigns bool `json:"email-campaigns,omitempty"`
	// Set this field to enable or disable SMS Marketing on the sub-account
	SmsCampaigns bool `json:"sms-campaigns,omitempty"`
	// Set this field to enable or disable Landing pages on the sub-account
	LandingPages bool `json:"landing-pages,omitempty"`
	// Set this field to enable or disable Transactional Email on the sub-account
	TransactionalEmails bool `json:"transactional-emails,omitempty"`
	// Set this field to enable or disable Transactional SMS on the sub-account
	TransactionalSms bool `json:"transactional-sms,omitempty"`
	// Set this field to enable or disable Facebook ads on the sub-account
	FacebookAds bool `json:"facebook-ads,omitempty"`
	// Set this field to enable or disable Web Push on the sub-account
	WebPush bool `json:"web-push,omitempty"`
	// Set this field to enable or disable Meetings on the sub-account
	Meetings bool `json:"meetings,omitempty"`
	// Set this field to enable or disable Conversations on the sub-account
	Conversations bool `json:"conversations,omitempty"`
	// Set this field to enable or disable Sales CRM on the sub-account
	Crm bool `json:"crm,omitempty"`
}
