/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * API version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package lib

type GetWhatsappCampaignsCampaigns struct {
	// ID of the WhatsApp Campaign
	Id int64 `json:"id"`
	// Name of the WhatsApp Campaign
	CampaignName string `json:"campaignName"`
	// Id of the WhatsApp template
	TemplateId string `json:"templateId"`
	// Status of the WhatsApp Campaign
	CampaignStatus string `json:"campaignStatus"`
	// UTC date-time on which WhatsApp campaign is scheduled. Should be in YYYY-MM-DDTHH:mm:ss.SSSZ format
	ScheduledAt string `json:"scheduledAt"`
	// Error reason in the campaign creation
	ErrorReason string `json:"errorReason,omitempty"`
	// Count of invalidated contacts
	InvalidatedContacts int64 `json:"invalidatedContacts,omitempty"`
	// Read percentage of the the WhatsApp campaign created
	ReadPercentage float32            `json:"readPercentage,omitempty"`
	Stats          *WhatsappCampStats `json:"stats,omitempty"`
	// Creation UTC date-time of the WhatsApp campaign (YYYY-MM-DDTHH:mm:ss.SSSZ)
	CreatedAt string `json:"createdAt"`
	// UTC date-time of last modification of the whatsapp template (YYYY-MM-DDTHH:mm:ss.SSSZ)
	ModifiedAt string `json:"modifiedAt"`
}
