/*
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * API version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package lib

type WhatsappCampTemplate struct {
	// name of the template
	Name string `json:"name,omitempty"`
	// description of the template
	Category string `json:"category,omitempty"`
	// language of the template
	Language       string `json:"language,omitempty"`
	ContainsButton bool   `json:"contains_button,omitempty"`
	DisplayHeader  bool   `json:"display_header,omitempty"`
	// type of header
	HeaderType string `json:"header_type,omitempty"`
	// array of component item objects
	Components []ComponentItems `json:"components,omitempty"`
	// array of variables item object
	HeaderVariables []VariablesItems `json:"header_variables,omitempty"`
	// array of variables item variables
	BodyVariables []VariablesItems `json:"body_variables,omitempty"`
	ButtonType    string           `json:"button_type,omitempty"`
	HideFooter    bool             `json:"hide_footer,omitempty"`
}
